<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Maui" Version="9.1.0" />
    <PackageVersion Include="IconPacks.Material" Version="1.0.8732.5-build" />
    <PackageVersion Include="IconPacks.MaterialCommunity" Version="1.0.8940.2-build" />
    <PackageVersion Include="Material.Components.Maui" Version="0.2.2-preview" />
    <PackageVersion Include="MaterialColorUtilities" Version="0.3.0" />
    <PackageVersion Include="MaterialColorUtilities.Maui" Version="0.3.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Maui.Controls" />
    <PackageVersion Include="Microsoft.Maui.Controls.Compatibility" />
    <PackageVersion Include="sqlite-net-pcl" Version="1.9.172" />
  </ItemGroup>
</Project>