namespace MusicPlayer
{
    public enum LocalizationKey
    {
        ago,
        browse,
        day,
        days,
        download,
        generalSettings,
        home,
        hour,
        hours,
        language,
        month,
        months,
        musicDirectory,
        noDirectorySelected,
        selectedDirectory,
        selectLanguage,
        settings,
        steps,
        test123,
        toggleLanguage,
        week,
        weeks,
        year,
        years
    }
}
